((name "3G门户")
 (id "And3G")
 (channel "AND0001")
 (version "5.2.2")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".3g")
 (meta-data
  (("GAME ID" "请在3G门户后台申请" "GAME_ID" #t "")
   ("CP ID" "请在3G门户后台申请" "CP_ID" #t "")))
 (manifest ())
 (resource ())
 (attention (("银联支付data.bin打unity包的时候必须放到drawable目录下"))))
