((name "37玩")
 (id "And37Wan")
 (channel "AND0002")
 (version "2.1")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".37w")
 (meta-data
  (("联运商ID" "请在后台申请" "" #f "pid")
   ("APP KEY" "请在后台申请" "Appkey" #t "key")
   ("APP ID" "请在后台申请" "" #f "gid")
   ("APP SECRET" "请在后台申请" "" #f "secret")
   ("兑换比率" "虚拟货币与人民币兑换比率，如10比1请填10" "And37W_RADIO" #t "")))
 (manifest ())
 (resource
  (((url "\\assets\\37wan_config.xml")
    (name "37玩配置文件")
    (description "请将文件assets\\37wan_config.xml复制到桌面，修改后导入。其中gameid设置为后台申请的APP ID"))))
 (attention ()))
