((name "4399手机开放平台")
 (id "And4399")
 (channel "AND0004")
 (version "2.7.0.3")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".m4399")
 (meta-data
  (("APP KEY" "请在后台申请" "APP_KEY" #t "")
   ("APP SECRET" "请在后台申请" "" #f "secrect")
   ("悬浮窗样式" "0：黄色；1：数字；2：豆娃；3：熊猫" "FLOAT_STYLE" #t "")
   ("调试模式" "true：打开调试模式；false：关闭调试模式。正式上线请设置为false" "DEBUG" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
