((name "7k7k游戏")
 (id "And7K7K")
 (channel "AND0019")
 (version "1.2.1.1")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".qike")
 (meta-data
  (("APP ID" "游戏应用标识" "QIKESDK_APPID" #f "appid")
   ("CP ID" "游戏合作厂商标识" "QIKESDK_CPUID" #f "")
   ("APP KEY" "客户端签名秘钥" "QIKESDK_APPKEY" #f "")
   ("APP SECRET" "服务端签名秘钥" "" #f "appsecret")
   ("PRIVATE KEY" "由此处值=md5(app_secret +\"7k7k\"+ app_key)，不是App_Secret，全小写 App_Secret 不允许保存在客户端" "QIKESDK_PRIVATEKEY" #f "")
   ("游戏名称" "必须与后台设置一致" "APP_NAME" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
