((name "爱游戏")
 (id "AndAiYouXi")
 (channel "AND0005")
 (version "4.1.6")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".ayx")
 (meta-data
  (("Client ID" "请在后台申请" "clientID" #t "clientId")
   ("Client Secret" "请在后台申请" "" #f "clientSecret")
   ("APP KEY" "请在后台申请" "" #f "appKey")
   ("调试模式" "true：调试模式，输出日志的tag为LAZY；false：生产模式" "EGAME_SDK_DEBUG" #f "")))

 (manifest ())
 (resource (((url "\\assets\\feeInfo.dat")
             (name "付费文件")
             (description "请从爱游戏后台下载"))))
 (attention ()))
