((name "安智市场")
 (id "AndAnZhi")
 (channel "AND0006")
 (version "3.5.2")
 (inner-version "2.1")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".anzhi")
 (meta-data
  (("APP KEY" "请在后台申请" "APP_KEY" #t "appKey")
   ("APP SECRET" "请在后台申请" "APP_SECRET" #t "appSecret")
   ("游戏名称" "请与安智后台保持一致" "APP_NAME" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
