((name "叉叉助手")
 (id "AndChaChaTools")
 (channel "AND0022")
 (version "1.0.8")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".guopan")
 (meta-data
  (("APP ID" "请在后台申请" "APP_ID" #t "appid")
   ("CLIENT SECRET KEY" "请在后台申请" "APP_KEY" #t "")
   ("SERVER SECRET KEY" "请在后台申请" "" #f "serverKey")
   ("DEBUG" "true：调试模式；false：上线模式" "DEBUG" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
