((name "当乐")
 (id "AndDangLe")
 (channel "AND0010")
 (version "4.2")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".downjoy")
 (meta-data
  (("MERCHANT ID" "厂商ID" "DOWNJOY_MERCHANT_ID" #t "")
   ("APP ID" "应用ID" "DOWNJOY_APP_ID" #t "appId")
   ("APP KEY" "应用秘钥" "DOWNJOY_APP_KEY" #t "appKey")
   ("PAYMENT KEY" "支付秘钥" "" #f "paymentKey")
   ("服务器编号" "请在当乐后台获取" "DOWNJOY_SERVER_SEQ_NUM" #t "")
   ("是否显示悬浮窗" "true：显示；false：不显示" "DOWNJOY_SHOW_FLOATBUTTON" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
