((name "聚乐游戏（HTC）")
 (id "AndHTC")
 (channel "AND0012")
 (version "5.0")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".htc")
 (meta-data
  (("API KEY" "金立API KEY" "APIKey" #t "apiKey")
   ("SECRET KEY" "金立SECRET KEY" "" #f "secretKey")
   ("PRIVATE KEY" "金立PRIVATE KEY" "" #f "privateKey")
   ("PUBLIC KEY" "金立PUBLIC KEY" "" #f "publicKey")
   ("支付回调地址" "请设置支付回调地址" "" #f "notifyUrl")))
 (manifest ())
 (resource ())
 (attention ()))
