((name "海马")
 (id "AndHaiMa")
 (channel "AND0011")
 (version "1.1.4")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".hm")
 (meta-data
  (("APP ID" "请在后台申请" "APP_ID" #t "appId")
   ("APP KEY" "请在后台申请" "" #f "appKey")
   ("游戏名称" "请与后台保持一致" "GAME_NAME" #t "")
   ("调试模式" "true：打开调试模式；false：关闭调试模式" "LOG_ENABLE" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
