((name "ITools安卓")
 (id "AndITools")
 (channel "AND0014")
 (version "1.1.4")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".itools.sky")
 (meta-data 
  (("APP ID" "请在ITools后台获取" "APP_ID" #f "appId")
   ("APP KEY" "请在ITools后台获取" "APP_KEY" #f "")))
 (manifest ())
 (resource ())
 (attention ()))
