((name "金立应用商店")
 (id "AndJinLi")
 (channel "AND0016")
 (version "3.0.7o")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #f)
 (unity-pack #f)
 (package-suffix ".am")
 (meta-data
  (("API KEY" "金立API KEY" "APIKey" #t "apiKey")
   ("SECRET KEY" "金立SECRET KEY" "" #f "secretKey")
   ("PRIVATE KEY" "金立PRIVATE KEY" "" #f "privateKey")
   ("PUBLIC KEY" "金立PUBLIC KEY" "" #f "publicKey")
   ("支付回调地址" "请设置支付回调地址" "" #f "notifyUrl")))
 (manifest ())
 (resource ())
 (attention ()))
