((name "快用")
 (id "AndKuaiYong")
 (channel "AND0018")
 (version "2.2.1")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #f)
 (package-suffix ".ky")
 (meta-data
  (("PAY ID" "请在后台申请" "HI_GAMEID" #f "")
   ("APP KEY" "请在后台申请" "HI_GAMEKEY" #f "appKey")
   ("RSA 公钥" "请在后台申请" "" #f "pubKey")
   ("横竖屏" "0：竖屏；1：横屏" "GAMESCREEN" #f "")))
 (manifest ())
 (resource ())
 (attention ()))
