((name "酷派应用商店")
 (id "AndKuPai")
 (channel "AND0026")
 (version "支付3.6.2+账号2.2.2")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".coolpad")
 (meta-data
  (("APP ID" "应用 ID" "APP_ID" #t "client_id")
   ("APP KEY" "账户密钥" "APP_KEY" #t "client_secret")
   ("PUBLIC KEY" "平台公钥" "PUBLIC_KEY" #t "pub_key")
   ("PRIATE KEY" "应用私钥：后台提供的私钥都是PKCS1格式的，但JAVA缺省只支持PKCS8格式，需要使用工具将私钥转换成PKCS8格式" "" #f "pri_key")
   ("数据统计 APP ID" "即APP ID，请按此格式填入：斜杠 + 空格 + APP ID，例如:\\ 123456789" "DC_APPID" #f "")))
 (manifest ())
 (resource ())
 (attention ()))
