((name "乐视TV")
 (id "AndLeShiTV")
 (channel "AND0028")
 (version "1.2.1")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #f)
 (package-suffix ".leshi")
 (meta-data
  (("APP ID" "APP ID" "lepay_appid" #f "client_id")
   ("APP KEY" "APP KEY" "lepay_appkey" #f "")
   ("APP SECRET" "请在后台申请" "" #f "privateKey")
   ("是否开启切换账号" "true：开启；false：关闭" "IS_CHANGE_ACCOUNT" #t "")
   ("支付回调地址" "必须与后台设置一致" "PAYNOTIFYURL" #t ""))) 
 (manifest ())
 (resource ())
 (attention ()))
