((name "魅族")
 (id "AndMeiZu")
 (channel "AND0029")
 (version "2.1")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".mz")
 (meta-data
  (("APP ID" "APP ID" "APP_ID" #t "appID")
   ("APP KEY" "APP KEY" "APP_KEY" #t "")
   ("APP SECRET" "APP SECRET" "" #f "appSecret")))
 (manifest ())
 (resource ())
 (attention ()))
