((name "木蚂蚁")
 (id "AndMuMaYi")
 (channel "AND0031")
 (version "3.1")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".mumayi")
 (meta-data
  (("APP KEY" "应用key，请在木蚂蚁后台申请" "APP_KEY" #t "appKey")
   ("APP NAME" "游戏名称" "APP_NAME" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
