((name "拇指玩")
 (id "AndMuZhiWan")
 (channel "AND0032")
 (version "3.0.9")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".mzw")
 (meta-data
  (("APP KEY" "APP KEY" "MZWAPPKEY" #f "appKey")
   ("DEBUG" "是否开启调试模式：true，开启；false：关闭。发布时，请置为false。" "DEBUG" #f "")
   ("签名校验串" "签名校验串" "" #f "signKey")))
 (manifest ())
 (resource ())
 (attention ()))
