((name "可可游戏中心（OPPO）")
 (id "AndOppo")
 (channel "AND0033")
 (version "2.0.3")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".nearme.gamecenter")
 (meta-data
  (("APP ID" "APP ID" "APP_ID" #t "")
   ("APP KEY" "APP KEY" "APP_KEY" #t "appKey")
   ("APP SECRET" "APP SECRET" "APP_SECRET" #t "appSecret")
   ("DEBUG" "true：开启调试模式；false：关闭调试模式" "BUGMODE" #t "")
   ("支付回调地址" "支付回调地址" "PAYNOTIFYURL" #t "")
   ("是否为单机游戏" "true为单机游戏；false为网游" "IS_ONLINE" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
