((name "朋友玩")
 (id "AndPengYouWan")
 (channel "AND0034")
 (version "1.2")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".pengyouwan")
 (meta-data
  (("GAME KEY" "请在朋友玩后台申请" "GAME_KEY" #t "")
   ("调试模式" "true：打开调试模式；false：关闭调试模式" "isDebug" #t "")
   ("支付回调秘钥" "cp payment callback secret" "" #f "apiSecret")))
 (manifest ())
 (resource ())
 (attention ()))
