((name "PPS")
 (id "AndPPS")
 (channel "AND0035")
 (version "4.0.0")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".pps")
 (meta-data
  (("GAME ID" "请在PPS后台申请" "APP_ID" #t "")
   ("登录 KEY" "请在PPS后台申请" "" #f "key")
   ("支付 KEY" "请在PPS后台申请" "" #f "payKey")))
 (manifest ())
 (resource
  (((url "\\assets\\zConfig\\pps_packetid.properties")
    (name "请配置渠道ID")
    (description "请在PPS后台申请渠道ID，然后在assets\\zConfig\\pps_packetid.properties中配置"))))
 (attention ()))
