((name "PPTV")
 (id "AndPPTV")
 (channel "AND0036")
 (version "4.4")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".pptv")
 (meta-data
  (("Game Id" "游戏ID" "GAME_ID" #t "")
   ("checkUpdate" "true：检测更新；false：不检测更新" "CHECKUPDATE" #t "")
   ("debug" "true：开启调试模式；false：关闭调试模式。上线前请改成false" "PptvVasSdk_DebugMode" #f "")
   ("Pay KEY" "支付KEY" "" #f "key")
   ("回调地址版本号" "请在PPTV后台申请" "notifyUrlVersion" #t "")
   ("友盟appKey" "友盟appKey" "UMENG_APPKEY" #f "")
   ("是否使用友盟统计" "true：使用；false：不使用" "useUmeng" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
