((name "搜狗手机游戏")
 (id "AndSouGou")
 (channel "AND0051")
 (version "1.4.29")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".sg")
 (meta-data
  (("游戏币名称" "请在后台申请" "CURRENCY" #t "")
   ("GID" "请在后台申请" "GID" #t "gid")
   ("调试模式" "true：打开调试模式；false：关闭调试模式" "DEVMODE" #t "")
   ("APP KEY" "请在后台申请" "APPKEY" #t "")
   ("APP SECRET" "请在后台申请" "" #f "secret")
   ("PAY KEY" "请在后台申请" "" #f "payKey")
   ("游戏名称" "请与后台保持一致" "APPNAME" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
