((name "新浪微游戏")
 (id "AndSina")
 (channel "AND0038")
 (version "1.2.3")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".wyx")
 (meta-data
   (("APP KEY" "在后台申请" "APP_KEY" #f "appKey")
    ("APP SECRET" "在后台申请" "" #f "appSecret")
    ("SIGNATURE KEY" "后台申请" "" #f "signaturekey")
    ("redirectUrl" "回调地址，后台申请" "sina_game_redirect" #f "")))
 (manifest
  ((application ((meta-data ((android:name "sina_game_appkey"))
                  ((Revalue ((android:value "sina_'APP_KEY'")))))))))
 (resource ())
 (attention ()))
