((name "xy助手")
 (id "AndXYTools")
 (channel "AND0045")
 (version "2.1")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".xy")
 (meta-data
  (("APP ID" "请在后台申请" "XYSDK_APPID" #t "appId")
   ("APP KEY" "请在后台申请" "XYSDK_APPKEY" #t "appKey")
   ("游戏名称" "请填写游戏名称，必须与后台一致" "APP_NAME" #t "")
   ("PAY KEY" "请在后台申请" "" #f "payKey")))
 (manifest ())
 (resource ())
 (attention ()))
