((name "小米应用商店")
 (id "AndXiaoMi")
 (channel "AND0043")
 (version "4.4.33")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #f)
 (unity-pack #t)
 (package-suffix ".xiao.mi")
 (meta-data
  (("APP ID" "请在小米后台申请" "XIAOMI_APP_ID" #t "appId")
   ("APP KEY" "请在小米后台申请" "XIAOMI_APP_KEY" #t "")
   ("APP SECRET" "请在小米后台申请" "" "#f" "appSecretKey")))
 (manifest ())
 (resource ())
 (attention ()))
