((name "有米偶玩")
 (id "AndYouMiOuWan")
 (channel "AND0046")
 (version "3.53")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".youmi")
 (meta-data
  (("APP ID" "请在后台申请" "APP_ID" #t "")
   ("APP SECRET" "请在后台申请" "APP_SECRET" #t "")
   ("SERVER SECRET" "请在后台申请" "" #f "serverSecret")
   ("支付方式" "true：固定额度，充值金额在支付页面不可修改；false：汇率模式，充值金额在支付页面可修改" "IS_FIXED_PAY" #t "")))
 (manifest ())
 (resource ())
 (attention ()))
