((name "游龙")
 (id "AndYouLong")
 (channel "AND0049")
 (version "1.8")
 (inner-version "2.0")
 (icon #f)
 (exit-dialog? #t)
 (unity-pack #t)
 (package-suffix ".yl")
 (meta-data
  (("APP ID" "请在后台申请" "PID" #f "pid")
   ("APP KEY" "请在后台申请" "PKEY" #f "pKey")))
 (manifest ())
 (resource ())
 (attention ()))
