((name "应用汇")
 (id "AndYingYongHui")
 (channel "AND0024")
 (version "6.2")
 (inner-version "2.0")
 (icon #t)
 (exit-dialog? #f)
 (unity-pack #f)
 (package-suffix ".yyh")
 (meta-data
  (("LOGIN ID" "登录ID" "YYH_LOGIN_ID" #t "loginId")
   ("LOGIN KEY" "登录KEY" "YYH_LOGIN_KEY" #t "loginKey")
   ("APP ID" "支付ID" "YYH_APP_ID" #t "appId")
   ("APP KEY" "支付KEY" "YYH_APP_KEY" #t "appKey")))
 (manifest ())
 (resource ())
 (attention (("add android-support-v4.jar"))))
